
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OjekWSImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9999/ws/OjekWS?wsdl")
public class OjekWSImplService
    extends Service
{

    private final static URL OJEKWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OJEKWSIMPLSERVICE_EXCEPTION;
    private final static QName OJEKWSIMPLSERVICE_QNAME = new QName("http://ws/", "OjekWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/OjekWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OJEKWSIMPLSERVICE_WSDL_LOCATION = url;
        OJEKWSIMPLSERVICE_EXCEPTION = e;
    }

    public OjekWSImplService() {
        super(__getWsdlLocation(), OJEKWSIMPLSERVICE_QNAME);
    }

    public OjekWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OJEKWSIMPLSERVICE_QNAME, features);
    }

    public OjekWSImplService(URL wsdlLocation) {
        super(wsdlLocation, OJEKWSIMPLSERVICE_QNAME);
    }

    public OjekWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OJEKWSIMPLSERVICE_QNAME, features);
    }

    public OjekWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OjekWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OjekWS
     */
    @WebEndpoint(name = "OjekWSImplPort")
    public OjekWS getOjekWSImplPort() {
        return super.getPort(new QName("http://ws/", "OjekWSImplPort"), OjekWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OjekWS
     */
    @WebEndpoint(name = "OjekWSImplPort")
    public OjekWS getOjekWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "OjekWSImplPort"), OjekWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OJEKWSIMPLSERVICE_EXCEPTION!= null) {
            throw OJEKWSIMPLSERVICE_EXCEPTION;
        }
        return OJEKWSIMPLSERVICE_WSDL_LOCATION;
    }

}
